spring.application.name=event-ledger
server.port=8082
spring.profiles.active=default
# SQLite database file location
spring.datasource.url=jdbc:sqlite:./eventledger.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate settings
spring.jpa.database-platform=com.mphasis.events.config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Custom path for Swagger UI
springdoc.swagger-ui.path=/my-custom-ui
# Custom path for the OpenAPI JSON description
springdoc.api-docs.path=/api-docs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1